In [2]:
path = 'Data/imdb_top_1000.csv'

In [48]:
import pandas as pd

df = pd.read_csv(path)

In [4]:
df.head()

,Poster_Link,Series_Title,Released_Year,Certificate,Runtime,Genre,IMDB_Rating,Overview,Meta_score,Director,Star1,Star2,Star3,Star4,No_of_Votes,Gross
0,https://m.media-amazon.com/images/M/MV5BMDFkYT...,The Shawshank Redemption,1994,A,142 min,Drama,9.3,Two imprisoned men bond over a number of years...,80.0,Frank Darabont,Tim Robbins,Morgan Freeman,Bob Gunton,William Sadler,2343110,"28,341,469"
1,https://m.media-amazon.com/images/M/MV5BM2MyNj...,The Godfather,1972,A,175 min,"Crime, Drama",9.2,An organized crime dynasty's aging patriarch t...,100.0,Francis Ford Coppola,Marlon Brando,Al Pacino,James Caan,Diane Keaton,1620367,"134,966,411"
2,https://m.media-amazon.com/images/M/MV5BMTMxNT...,The Dark Knight,2008,UA,152 min,"Action, Crime, Drama",9.0,When the menace known as the Joker wreaks havo...,84.0,Christopher Nolan,Christian Bale,Heath Ledger,Aaron Eckhart,Michael Caine,2303232,"534,858,444"
3,https://m.media-amazon.com/images/M/MV5BMWMwMG...,The Godfather: Part II,1974,A,202 min,"Crime, Drama",9.0,The early life and career of Vito Corleone in ...,90.0,Francis Ford Coppola,Al Pacino,Robert De Niro,Robert Duvall,Diane Keaton,1129952,"57,300,000"
4,https://m.media-amazon.com/images/M/MV5BMWU4N2...,12 Angry Men,1957,U,96 min,"Crime, Drama",9.0,A jury holdout attempts to prevent a miscarria...,96.0,Sidney Lumet,Henry Fonda,Lee J. Cobb,Martin Balsam,John Fiedler,689845,"4,360,000"

In [49]:
# Get rid of useless columns

df.drop(['Poster_Link', 'Certificate'], axis=1, inplace=True)

In [9]:
df.head()

,Series_Title,Released_Year,Runtime,Genre,IMDB_Rating,Overview,Meta_score,Director,Star1,Star2,Star3,Star4,No_of_Votes,Gross
0,The Shawshank Redemption,1994,142 min,Drama,9.3,Two imprisoned men bond over a number of years...,80.0,Frank Darabont,Tim Robbins,Morgan Freeman,Bob Gunton,William Sadler,2343110,"28,341,469"
1,The Godfather,1972,175 min,"Crime, Drama",9.2,An organized crime dynasty's aging patriarch t...,100.0,Francis Ford Coppola,Marlon Brando,Al Pacino,James Caan,Diane Keaton,1620367,"134,966,411"
2,The Dark Knight,2008,152 min,"Action, Crime, Drama",9.0,When the menace known as the Joker wreaks havo...,84.0,Christopher Nolan,Christian Bale,Heath Ledger,Aaron Eckhart,Michael Caine,2303232,"534,858,444"
3,The Godfather: Part II,1974,202 min,"Crime, Drama",9.0,The early life and career of Vito Corleone in ...,90.0,Francis Ford Coppola,Al Pacino,Robert De Niro,Robert Duvall,Diane Keaton,1129952,"57,300,000"
4,12 Angry Men,1957,96 min,"Crime, Drama",9.0,A jury holdout attempts to prevent a miscarria...,96.0,Sidney Lumet,Henry Fonda,Lee J. Cobb,Martin Balsam,John Fiedler,689845,"4,360,000"

In [10]:
# Oldest movie
df['Released_Year'] = pd.to_numeric(df['Released_Year'], errors='coerce')
oldest = df.iloc[df['Released_Year'].idxmin()]
oldest

Series_Title                          Das Cabinet des Dr. Caligari
Released_Year                                               1920.0
Runtime                                                     76 min
Genre                                     Fantasy, Horror, Mystery
IMDB_Rating                                                    8.1
Overview         Hypnotist Dr. Caligari uses a somnambulist, Ce...
Meta_score                                                     NaN
Director                                              Robert Wiene
Star1                                                Werner Krauss
Star2                                                 Conrad Veidt
Star3                                              Friedrich Feher
Star4                                                  Lil Dagover
No_of_Votes                                                  57428
Gross                                                          NaN
Name: 321, dtype: object

In [11]:
# Newest Movie
newest = df.iloc[df['Released_Year'].idxmax()]
newest

Series_Title                                              Hamilton
Released_Year                                               2020.0
Runtime                                                    160 min
Genre                                    Biography, Drama, History
IMDB_Rating                                                    8.6
Overview         The real life of one of America's foremost fou...
Meta_score                                                    90.0
Director                                               Thomas Kail
Star1                                           Lin-Manuel Miranda
Star2                                                 Phillipa Soo
Star3                                              Leslie Odom Jr.
Star4                                       Renée Elise Goldsberry
No_of_Votes                                                  55291
Gross                                                          NaN
Name: 18, dtype: object

In [21]:
# Top 10 Movies
df.sort_values(['IMDB_Rating', 'Series_Title'], ascending=[False, True]).head(10)

,Series_Title,Released_Year,Runtime,Genre,IMDB_Rating,Overview,Meta_score,Director,Star1,Star2,Star3,Star4,No_of_Votes,Gross
0,The Shawshank Redemption,1994.0,142 min,Drama,9.3,Two imprisoned men bond over a number of years...,80.0,Frank Darabont,Tim Robbins,Morgan Freeman,Bob Gunton,William Sadler,2343110,"28,341,469"
1,The Godfather,1972.0,175 min,"Crime, Drama",9.2,An organized crime dynasty's aging patriarch t...,100.0,Francis Ford Coppola,Marlon Brando,Al Pacino,James Caan,Diane Keaton,1620367,"134,966,411"
4,12 Angry Men,1957.0,96 min,"Crime, Drama",9.0,A jury holdout attempts to prevent a miscarria...,96.0,Sidney Lumet,Henry Fonda,Lee J. Cobb,Martin Balsam,John Fiedler,689845,"4,360,000"
2,The Dark Knight,2008.0,152 min,"Action, Crime, Drama",9.0,When the menace known as the Joker wreaks havo...,84.0,Christopher Nolan,Christian Bale,Heath Ledger,Aaron Eckhart,Michael Caine,2303232,"534,858,444"
3,The Godfather: Part II,1974.0,202 min,"Crime, Drama",9.0,The early life and career of Vito Corleone in ...,90.0,Francis Ford Coppola,Al Pacino,Robert De Niro,Robert Duvall,Diane Keaton,1129952,"57,300,000"
6,Pulp Fiction,1994.0,154 min,"Crime, Drama",8.9,"The lives of two mob hitmen, a boxer, a gangst...",94.0,Quentin Tarantino,John Travolta,Uma Thurman,Samuel L. Jackson,Bruce Willis,1826188,"107,928,762"
7,Schindler's List,1993.0,195 min,"Biography, Drama, History",8.9,"In German-occupied Poland during World War II,...",94.0,Steven Spielberg,Liam Neeson,Ralph Fiennes,Ben Kingsley,Caroline Goodall,1213505,"96,898,818"
5,The Lord of the Rings: The Return of the King,2003.0,201 min,"Action, Adventure, Drama",8.9,Gandalf and Aragorn lead the World of Men agai...,94.0,Peter Jackson,Elijah Wood,Viggo Mortensen,Ian McKellen,Orlando Bloom,1642758,"377,845,905"
9,Fight Club,1999.0,139 min,Drama,8.8,An insomniac office worker and a devil-may-car...,66.0,David Fincher,Brad Pitt,Edward Norton,Meat Loaf,Zach Grenier,1854740,"37,030,102"
11,Forrest Gump,1994.0,142 min,"Drama, Romance",8.8,"The presidencies of Kennedy and Johnson, the e...",82.0,Robert Zemeckis,Tom Hanks,Robin Wright,Gary Sinise,Sally Field,1809221,"330,252,182"
12,"Il buono, il brutto, il cattivo",1966.0,161 min,Western,8.8,A bounty hunting scam joins two men in an unea...,90.0,Sergio Leone,Clint Eastwood,Eli Wallach,Lee Van Cleef,Aldo Giuffrè,688390,"6,100,000"
8,Inception,2010.0,148 min,"Action, Adventure, Sci-Fi",8.8,A thief who steals corporate secrets through t...,74.0,Christopher Nolan,Leonardo DiCaprio,Joseph Gordon-Levitt,Elliot Page,Ken Watanabe,2067042,"292,576,195"
10,The Lord of the Rings: The Fellowship of the Ring,2001.0,178 min,"Action, Adventure, Drama",8.8,A meek Hobbit from the Shire and eight compani...,92.0,Peter Jackson,Elijah Wood,Ian McKellen,Orlando Bloom,Sean Bean,1661481,"315,544,750"
15,Goodfellas,1990.0,146 min,"Biography, Crime, Drama",8.7,The story of Henry Hill and his life in the mo...,90.0,Martin Scorsese,Robert De Niro,Ray Liotta,Joe Pesci,Lorraine Bracco,1020727,"46,836,394"
17,One Flew Over the Cuckoo's Nest,1975.0,133 min,Drama,8.7,A criminal pleads insanity and is admitted to ...,83.0,Milos Forman,Jack Nicholson,Louise Fletcher,Michael Berryman,Peter Brocco,918088,"112,000,000"

In [28]:
df['Genre'] = df['Genre'].str.split(', ')
df.head()

,Series_Title,Released_Year,Runtime,Genre,IMDB_Rating,Overview,Meta_score,Director,Star1,Star2,Star3,Star4,No_of_Votes,Gross
0,The Shawshank Redemption,1994,142 min,[Drama],9.3,Two imprisoned men bond over a number of years...,80.0,Frank Darabont,Tim Robbins,Morgan Freeman,Bob Gunton,William Sadler,2343110,"28,341,469"
1,The Godfather,1972,175 min,"[Crime, Drama]",9.2,An organized crime dynasty's aging patriarch t...,100.0,Francis Ford Coppola,Marlon Brando,Al Pacino,James Caan,Diane Keaton,1620367,"134,966,411"
2,The Dark Knight,2008,152 min,"[Action, Crime, Drama]",9.0,When the menace known as the Joker wreaks havo...,84.0,Christopher Nolan,Christian Bale,Heath Ledger,Aaron Eckhart,Michael Caine,2303232,"534,858,444"
3,The Godfather: Part II,1974,202 min,"[Crime, Drama]",9.0,The early life and career of Vito Corleone in ...,90.0,Francis Ford Coppola,Al Pacino,Robert De Niro,Robert Duvall,Diane Keaton,1129952,"57,300,000"
4,12 Angry Men,1957,96 min,"[Crime, Drama]",9.0,A jury holdout attempts to prevent a miscarria...,96.0,Sidney Lumet,Henry Fonda,Lee J. Cobb,Martin Balsam,John Fiedler,689845,"4,360,000"

In [30]:
df2 = df.explode('Genre')
df2.head()

,Series_Title,Released_Year,Runtime,Genre,IMDB_Rating,Overview,Meta_score,Director,Star1,Star2,Star3,Star4,No_of_Votes,Gross
0,The Shawshank Redemption,1994,142 min,Drama,9.3,Two imprisoned men bond over a number of years...,80.0,Frank Darabont,Tim Robbins,Morgan Freeman,Bob Gunton,William Sadler,2343110,"28,341,469"
1,The Godfather,1972,175 min,Crime,9.2,An organized crime dynasty's aging patriarch t...,100.0,Francis Ford Coppola,Marlon Brando,Al Pacino,James Caan,Diane Keaton,1620367,"134,966,411"
1,The Godfather,1972,175 min,Drama,9.2,An organized crime dynasty's aging patriarch t...,100.0,Francis Ford Coppola,Marlon Brando,Al Pacino,James Caan,Diane Keaton,1620367,"134,966,411"
2,The Dark Knight,2008,152 min,Action,9.0,When the menace known as the Joker wreaks havo...,84.0,Christopher Nolan,Christian Bale,Heath Ledger,Aaron Eckhart,Michael Caine,2303232,"534,858,444"
2,The Dark Knight,2008,152 min,Crime,9.0,When the menace known as the Joker wreaks havo...,84.0,Christopher Nolan,Christian Bale,Heath Ledger,Aaron Eckhart,Michael Caine,2303232,"534,858,444"

In [45]:
# Highest grossing movie for each genre
df['Genre'] = df['Genre'].str.split(', ')
df2 = df.explode('Genre')
df2.reset_index(drop=True, inplace=True)
df2.loc[df2.groupby(['Genre'])['IMDB_Rating'].idxmax()]

,Series_Title,Released_Year,Runtime,Genre,IMDB_Rating,Overview,Meta_score,Director,Star1,Star2,Star3,Star4,No_of_Votes,Gross
3,The Dark Knight,2008,152 min,Action,9.0,When the menace known as the Joker wreaks havo...,84.0,Christopher Nolan,Christian Bale,Heath Ledger,Aaron Eckhart,Michael Caine,2303232,"534,858,444"
11,The Lord of the Rings: The Return of the King,2003,201 min,Adventure,8.9,Gandalf and Aragorn lead the World of Men agai...,94.0,Peter Jackson,Elijah Wood,Viggo Mortensen,Ian McKellen,Orlando Bloom,1642758,"377,845,905"
52,Sen to Chihiro no kamikakushi,2001,125 min,Animation,8.6,"During her family's move to the suburbs, a sul...",96.0,Hayao Miyazaki,Daveigh Chase,Suzanne Pleshette,Miyu Irino,Rumi Hiiragi,651376,"10,055,859"
15,Schindler's List,1993,195 min,Biography,8.9,"In German-occupied Poland during World War II,...",94.0,Steven Spielberg,Liam Neeson,Ralph Fiennes,Ben Kingsley,Caroline Goodall,1213505,"96,898,818"
43,Gisaengchung,2019,132 min,Comedy,8.6,Greed and class discrimination threaten the ne...,96.0,Bong Joon Ho,Kang-ho Song,Lee Sun-kyun,Cho Yeo-jeong,Choi Woo-sik,552778,"53,367,844"
1,The Godfather,1972,175 min,Crime,9.2,An organized crime dynasty's aging patriarch t...,100.0,Francis Ford Coppola,Marlon Brando,Al Pacino,James Caan,Diane Keaton,1620367,"134,966,411"
0,The Shawshank Redemption,1994,142 min,Drama,9.3,Two imprisoned men bond over a number of years...,80.0,Frank Darabont,Tim Robbins,Morgan Freeman,Bob Gunton,William Sadler,2343110,"28,341,469"
54,Sen to Chihiro no kamikakushi,2001,125 min,Family,8.6,"During her family's move to the suburbs, a sul...",96.0,Hayao Miyazaki,Daveigh Chase,Suzanne Pleshette,Miyu Irino,Rumi Hiiragi,651376,"10,055,859"
38,Star Wars: Episode V - The Empire Strikes Back,1980,124 min,Fantasy,8.7,After the Rebels are brutally overpowered by t...,82.0,Irvin Kershner,Mark Hamill,Harrison Ford,Carrie Fisher,Billy Dee Williams,1159315,"290,475,067"
206,Sunset Blvd.,1950,110 min,Film-Noir,8.4,A screenwriter develops a dangerous relationsh...,NaN,Billy Wilder,William Holden,Gloria Swanson,Erich von Stroheim,Nancy Olson,201632,NaN
17,Schindler's List,1993,195 min,History,8.9,"In German-occupied Poland during World War II,...",94.0,Steven Spielberg,Liam Neeson,Ralph Fiennes,Ben Kingsley,Caroline Goodall,1213505,"96,898,818"
122,Psycho,1960,109 min,Horror,8.5,"A Phoenix secretary embezzles $40,000 from her...",97.0,Alfred Hitchcock,Anthony Perkins,Janet Leigh,Vera Miles,John Gavin,604211,"32,000,000"
85,Whiplash,2014,106 min,Music,8.5,A promising young drummer enrolls at a cut-thr...,88.0,Damien Chazelle,Miles Teller,J.K. Simmons,Melissa Benoist,Paul Reiser,717585,"13,092,000"
193,Anand,1971,122 min,Musical,8.4,The story of a terminally ill man who wishes t...,NaN,Hrishikesh Mukherjee,Rajesh Khanna,Amitabh Bachchan,Sumita Sanyal,Ramesh Deo,30273,NaN
65,Se7en,1995,127 min,Mystery,8.6,"Two detectives, a rookie and a veteran, hunt a...",65.0,David Fincher,Morgan Freeman,Brad Pitt,Kevin Spacey,Andrew Kevin Walker,1445096,"100,125,643"
26,Forrest Gump,1994,142 min,Romance,8.8,"The presidencies of Kennedy and Johnson, the e...",82.0,Robert Zemeckis,Tom Hanks,Robin Wright,Gary Sinise,Sally Field,1809221,"330,252,182"
20,Inception,2010,148 min,Sci-Fi,8.8,A thief who steals corporate secrets through t...,74.0,Christopher Nolan,Leonardo DiCaprio,Joseph Gordon-Levitt,Elliot Page,Ken Watanabe,2067042,"292,576,195"
246,Bacheha-Ye aseman,1997,89 min,Sport,8.3,"After a boy loses his sister's pair of shoes, ...",77.0,Majid Majidi,Mohammad Amir Naji,Amir Farrokh Hashemian,Bahare Seddiqi,Nafise Jafar-Mohammadi,65341,"933,933"
45,Gisaengchung,2019,132 min,Thriller,8.6,Greed and class discrimination threaten the ne...,96.0,Bong Joon Ho,Kang-ho Song,Lee Sun-kyun,Cho Yeo-jeong,Choi Woo-sik,552778,"53,367,844"
56,Saving Private Ryan,1998,169 min,War,8.6,"Following the Normandy Landings, a group of U....",91.0,Steven Spielberg,Tom Hanks,Matt Damon,Tom Sizemore,Edward Burns,1235804,"216,540,909"
27,"Il buono, il brutto, il cattivo",1966,161 min,Western,8.8,A bounty hunting scam joins two men in an unea...,90.0,Sergio Leone,Clint Eastwood,Eli Wallach,Lee Van Cleef,Aldo Giuffrè,688390,"6,100,000"

In [40]:
# Star with the most movies
df3 = df[['Star1', 'Star2', 'Star3', 'Star4']]
df3.melt(var_name='columns', value_name='name').drop('columns', axis=1).value_counts()

name
Robert De Niro    17
Tom Hanks         14
Al Pacino         13
Brad Pitt         12
Clint Eastwood    12
                  ..
Jack Benny         1
Jack Kehoe         1
Jack McBrayer      1
Jack Oakie         1
Özge Özberk        1
Length: 2709, dtype: int64

In [35]:
# Director with the most movies
df['Director'].value_counts()

Alfred Hitchcock    14
Steven Spielberg    13
Hayao Miyazaki      11
Martin Scorsese     10
Akira Kurosawa      10
                    ..
Neill Blomkamp       1
Tomas Alfredson      1
Duncan Jones         1
Jacques Audiard      1
George Stevens       1
Name: Director, Length: 548, dtype: int64

In [50]:
df['Gross'] = df['Gross'].str.replace(',', '', regex=False)

In [51]:
df['Gross'] = df['Gross'].apply(pd.to_numeric, errors='coerce')

In [43]:
df['Gross'] = df['Gross'].fillna(0)

In [57]:
# Highest Grossing Movie by Director
df = df.dropna(subset=['Gross'])
df.loc[df.groupby("Director")['Gross'].idxmin()].sort_values('Gross', ascending=True).head(15)

,Series_Title,Released_Year,Runtime,Genre,IMDB_Rating,Overview,Meta_score,Director,Star1,Star2,Star3,Star4,No_of_Votes,Gross
630,Adams æbler,2005,94 min,"Comedy, Crime, Drama",7.8,A neo-nazi sentenced to community service at a...,51.0,Anders Thomas Jensen,Ulrich Thomsen,Mads Mikkelsen,Nicolas Bro,Paprika Steen,45717,1305.0
390,Knockin' on Heaven's Door,1997,87 min,"Action, Crime, Comedy",8.0,Two terminally ill patients escape from a hosp...,NaN,Thomas Jahn,Til Schweiger,Jan Josef Liefers,Thierry van Werveke,Moritz Bleibtreu,27721,3296.0
624,Mr. Nobody,2009,141 min,"Drama, Fantasy, Romance",7.8,A boy stands on a station platform as a train ...,63.0,Jaco Van Dormael,Jared Leto,Sarah Polley,Diane Kruger,Linh Dan Pham,216421,3600.0
926,Dead Man's Shoes,2004,90 min,"Crime, Drama, Thriller",7.6,A disaffected soldier returns to his hometown ...,52.0,Shane Meadows,Paddy Considine,Gary Stretch,Toby Kebbell,Stuart Wolfenden,49728,6013.0
605,Ajeossi,2010,119 min,"Action, Crime, Drama",7.8,A quiet pawnshop keeper with a violent past ta...,NaN,Jeong-beom Lee,Won Bin,Sae-ron Kim,Tae-hoon Kim,Hee-won Kim,62848,6460.0
141,Udaan,2010,134 min,Drama,8.2,"Expelled from his school, a 16-year old boy re...",NaN,Vikramaditya Motwane,Rajat Barmecha,Ronit Roy,Manjot Singh,Ram Kapoor,42341,7461.0
356,Tropa de Elite,2007,115 min,"Action, Crime, Drama",8.0,"In 1997 Rio de Janeiro, Captain Nascimento has...",33.0,José Padilha,Wagner Moura,André Ramiro,Caio Junqueira,Milhem Cortaz,98097,8060.0
190,All About Eve,1950,138 min,Drama,8.2,A seemingly timid but secretly ruthless ingénu...,98.0,Joseph L. Mankiewicz,Bette Davis,Anne Baxter,George Sanders,Celeste Holm,120539,10177.0
350,Dev.D,2009,144 min,"Drama, Romance",8.0,After breaking up with his childhood sweethear...,NaN,Anurag Kashyap,Abhay Deol,Mahie Gill,Kalki Koechlin,Dibyendu Bhattacharya,28749,10950.0
187,Dial M for Murder,1954,105 min,"Crime, Thriller",8.2,A former tennis player tries to arrange his wi...,75.0,Alfred Hitchcock,Ray Milland,Grace Kelly,Robert Cummings,John Williams,158335,12562.0
239,Salinui chueok,2003,131 min,"Crime, Drama, Mystery",8.1,"In a small Korean province in 1986, two detect...",82.0,Bong Joon Ho,Kang-ho Song,Kim Sang-kyung,Roe-ha Kim,Jae-ho Song,139558,14131.0
636,Ondskan,2003,113 min,Drama,7.8,A teenage boy expelled from school for fightin...,61.0,Mikael Håfström,Andreas Wilson,Henrik Lundström,Gustaf Skarsgård,Linda Zilliacus,35682,15280.0
52,City Lights,1931,87 min,"Comedy, Drama, Romance",8.5,"With the aid of a wealthy erratic tippler, a d...",99.0,Charles Chaplin,Charles Chaplin,Virginia Cherrill,Florence Lee,Harry Myers,167839,19181.0
317,La passion de Jeanne d'Arc,1928,110 min,"Biography, Drama, History",8.1,"In 1431, Jeanne d'Arc is placed on trial on ch...",NaN,Carl Theodor Dreyer,Maria Falconetti,Eugene Silvain,André Berley,Maurice Schutz,47676,21877.0
648,The Boondock Saints,1999,108 min,"Action, Crime, Thriller",7.8,Two Irish Catholic brothers become vigilantes ...,44.0,Troy Duffy,Willem Dafoe,Sean Patrick Flanery,Norman Reedus,David Della Rocco,227143,25812.0

In [ ]:
# Save the dataframe as parquet
df.to_parquet('Data/imdb.parquet')